import = ["/home/dminh/.config/alacritty/theme.toml"]

[font]
size = 13

[font.bold]
family = "JetkaBoldSemi Nerd Font Extended"
style = "Regular"

[font.bold_italic]
family = "JetkaBoldSemi Nerd Font Extended"
style = "Italic"

[font.italic]
family = "JetkaSemi Nerd Font Extended"
style = "Italic"

[font.normal]
family = "JetkaSemi Nerd Font Extended"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
history = 2000
multiplier = 3

[shell]
program = "/bin/fish"
args = ["-l", "-c", "tmux"]

[env]
TERM = "xterm-256color"

[window]
dynamic_title = true
title = "alacritty"

[window.class]
general = "alacritty"
instance = "alacritty"

[window.padding]
x = 0
y = 0
