import = ["/home/dminh/.config/alacritty/theme.toml"]

[font]
size = 13

[font.bold]
family = "Jetka Nerd Font Extended"
style = "Bold"

[font.bold_italic]
family = "Jetka Nerd Font Extended"
style = "Bold Italic"

[font.italic]
family = "Jetka Nerd Font Extended"
style = "Regular Italic"

[font.normal]
family = "Jetka Nerd Font Extended"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[scrolling]
history = 2000
multiplier = 3

[shell]
program = "/bin/fish"

[window]
dynamic_title = true
title = "alacritty"

[window.class]
general = "alacritty"
instance = "alacritty"

[window.padding]
x = 0
y = 0
