# Crux Midnight for Alacritty
# ~/.config/alacritty/theme.toml
[colors.bright]
black = "#5f5f67"
blue = "#8696f7"
cyan = "#7adbce"
green = "#b3d57d"
magenta = "#d699b6"
red = "#e66c6e"
white = "#c0c8e9"
yellow = "#d9c574"

[colors.cursor]
cursor = "#c0c8e9"
text = "#1a1b26"

[colors.footer_bar]
background = "#a3aac6"
foreground = "#161720"

[colors.hints.end]
background = "#161720"
foreground = "#868ca3"

[colors.hints.start]
background = "#a3aac6"
foreground = "#161720"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#5f5f67"
blue = "#8696f7"
cyan = "#7adbce"
green = "#b3d57d"
magenta = "#d699b6"
red = "#e66c6e"
white = "#c0c8e9"
yellow = "#d9c574"

[colors.primary]
background = "#161720"
bright_foreground = "#c0c8e9"
dim_foreground = "#a3aac6"
foreground = "#c0c8e9"

[colors.search.focused_match]
background = "#8696f7"
foreground = "#1a1b26"

[colors.search.matches]
background = "#e66c6e"
foreground = "#c0c8e9"

[colors.selection]
background = "#23242e"
text = "#c0c8e9"

[colors.vi_mode_cursor]
cursor = "#c0c8e9"
text = "#1a1b26"
    