# Crux Midnight for Alacritty
# ~/.config/alacritty/theme.toml
[colors.bright]
black = "#6b6c73"
blue = "#6d80ed"
cyan = "#7adbce"
green = "#b3d57d"
magenta = "#cd84a7"
red = "#e66c6e"
white = "#b3bde4"
yellow = "#d9c574"

[colors.cursor]
cursor = "#b3bde4"
text = "#1c1d28"

[colors.footer_bar]
background = "#98a1c2"
foreground = "#181922"

[colors.hints.end]
background = "#181922"
foreground = "#7d84a0"

[colors.hints.start]
background = "#98a1c2"
foreground = "#181922"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#6b6c73"
blue = "#6d80ed"
cyan = "#7adbce"
green = "#b3d57d"
magenta = "#cd84a7"
red = "#e66c6e"
white = "#b3bde4"
yellow = "#d9c574"

[colors.primary]
background = "#181922"
bright_foreground = "#b3bde4"
dim_foreground = "#98a1c2"
foreground = "#b3bde4"

[colors.search.focused_match]
background = "#b3d57d"
foreground = "#1c1d28"

[colors.search.matches]
background = "#e66c6e"
foreground = "#b3bde4"

[colors.selection]
background = "#252530"
text = "#b3bde4"

[colors.vi_mode_cursor]
cursor = "#b3bde4"
text = "#1c1d28"
    