# Darkoma for Alacritty
# ~/.config/alacritty/theme.yml
colors:
  primary:
    background: '#233435'
    foreground: '#ccdcdd'
    dim_foreground: '#8fb3b5'
    bright_foreground: '#e0eaea'
  cursor:
    text: '#233435'
    cursor: '#8fd780'
  vi_mode_cursor:
    text: '#233435'
    cursor: '#8fd780'
  search:
    matches:
      foreground: '#375153'
      background: '#b28ff5'
    focused_match:
      foreground: '#b28ff5'
      background: '#375153'
  hints:
    start:
      foreground: '#375153'
      background: '#e6dd90'
    end:
      foreground: '#e6dd90'
      background: '#375153'
  line_indicator:
    foreground: None
    background: None
  footer_bar:
    foreground: '#375153'
    background: '#b28ff5'
  selection:
    text: '#ccdcdd'
    background: '#416062'
  normal:
    black: '#3d5b5b'
    red: '#f36a6f'
    green: '#8fd780'
    yellow: '#e6dd90'
    blue: '#62b1ff'
    magenta: '#e67aca'
    cyan: '#5ddae2'
    white: '#f4f8f8'
  bright:
    black: '#3d5b5b'
    red: '#f36a6f'
    green: '#8fd780'
    yellow: '#e6dd90'
    blue: '#62b1ff'
    magenta: '#e67aca'
    cyan: '#5ddae2'
    white: '#f4f8f8'
    