[colors.bright]
black = "#2D4452"
blue = "#619af5"
cyan = "#42b8e6"
green = "#a4c76f"
magenta = "#9d78d1"
red = "#f15a5d"
white = "#abc2d0"
yellow = "#eace60"

[colors.cursor]
cursor = "#DBE5EB"
text = "#10181d"

[colors.footer_bar]
background = "#9d78d1"
foreground = "#1D2C35"

[colors.hints.end]
background = "#1D2C35"
foreground = "#eace60"

[colors.hints.start]
background = "#eace60"
foreground = "#1D2C35"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#2D4452"
blue = "#619af5"
cyan = "#42b8e6"
green = "#a4c76f"
magenta = "#9d78d1"
red = "#f15a5d"
white = "#abc2d0"
yellow = "#eace60"

[colors.primary]
background = "#0E161A"
bright_foreground = "#DBE5EB"
dim_foreground = "#5C88A3"
foreground = "#abc2d0"

[colors.search.focused_match]
background = "#1D2C35"
foreground = "#9d78d1"

[colors.search.matches]
background = "#9d78d1"
foreground = "#1D2C35"

[colors.selection]
background = "#243642"
text = "#abc2d0"

[colors.vi_mode_cursor]
cursor = "#DBE5EB"
text = "#10181d"
