# Crux Alpha Green for Alacritty
# ~/.config/alacritty/theme.toml
[colors.bright]
black = "#45535b"
blue = "#6c86db"
cyan = "#76b4cc"
green = "#a7c080"
magenta = "#b495d3"
red = "#e67e80"
white = "#eeebe9"
yellow = "#dbbc7f"

[colors.cursor]
cursor = "#cfc7c2"
text = "#242b2f"

[colors.footer_bar]
background = "#b3a69e"
foreground = "#1e2427"

[colors.hints.end]
background = "#1e2427"
foreground = "#96857a"

[colors.hints.start]
background = "#b3a69e"
foreground = "#1e2427"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#45535b"
blue = "#6c86db"
cyan = "#76b4cc"
green = "#a7c080"
magenta = "#b495d3"
red = "#e67e80"
white = "#eeebe9"
yellow = "#dbbc7f"

[colors.primary]
background = "#1e2427"
bright_foreground = "#eeebe9"
dim_foreground = "#b3a69e"
foreground = "#cfc7c2"

[colors.search.focused_match]
background = "#a7c080"
foreground = "#242b2f"

[colors.search.matches]
background = "#e67e80"
foreground = "#eeebe9"

[colors.selection]
background = "#2b3439"
text = "#cfc7c2"

[colors.vi_mode_cursor]
cursor = "#eeebe9"
text = "#242b2f"

