#!/bin/fish

function clamp
  set min $argv[1]
  set max $argv[2]
  set val $argv[3]
  python -c "print(max($min, min($val, $max)))"
end

set direction $argv[1]
set current $argv[2]

if test $direction = "down"
  set target (clamp 1 6 (math $current+1))
  hyprctl dispatch workspace $target
else
  set target (clamp 1 6 (math $current-1))
  hyprctl dispatch workspace $target
end
