#!/bin/fish

set bar eww --config ~/.config/eww/bar

function spawn
    swayidle -w \
        timeout 300 '~/.dotfiles/scripts/locker lock' \
        timeout 600 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' \
        && sleep 5 && eww --config $HOME/.config/eww/locker open locker \
        && sleep 5 && eww --config $HOME/.config/eww/bar open bar \
        && sleep 5 && hyprpaper
end

function toggle
    set idle_state (pgrep swayidle)

    if test -n "$idle_state"
        $bar update idle_icon=
        pkill -SIGTERM swayidle
    else
        $bar update idle_icon=
        spawn &
    end
end

switch $argv[1]
    case ''
        spawn
    case toggle
        toggle
end
