#!/bin/fish

function run-portal
    sleep 1
    killall -e xdg-desktop-portal-hyprland
    killall -e xdg-desktop-portal-wlr
    killall xdg-desktop-portal
    /usr/lib/xdg-desktop-portal-hyprland &
    sleep 2
    /usr/lib/xdg-desktop-portal &
end

function import-gsettings
    set GTK_CONFIG "$HOME/.config/gtk-3.0/settings.ini"
    if not test -e $GTK_CONFIG
        exit 1
    end

    set gnome_schema "org.gnome.desktop.interface"
    set gtk_theme (grep 'gtk-theme-name' "$config" | sed 's/.*\s*=\s*//')
    set icon_theme (grep 'gtk-icon-theme-name' "$config" | sed 's/.*\s*=\s*//')
    set cursor_theme (grep 'gtk-cursor-theme-name' "$config" | sed 's/.*\s*=\s*//')
    set font_name (grep 'gtk-font-name' "$config" | sed 's/.*\s*=\s*//')

    gsettings set "$gnome_schema" gtk-theme "$gtk_theme"
    gsettings set "$gnome_schema" icon-theme "$icon_theme"
    gsettings set "$gnome_schema" cursor-theme "$cursor_theme"
    gsettings set "$gnome_schema" font-name "$font_name"
    gsettings set org.gnome.desktop.wm.preferences button-layout ""
end

set STATUSBAR eww --config ~/.config/eww

function toggle-idle
    set idle_state (pgrep swayidle)

    if test -n "$idle_state"
        $STATUSBAR update idle_icon=
    else
        $STATUSBAR update idle_icon=
    end
end


function toggle-nightlight
    set pid (pgrep wlsunset)

    if test -n "$pid"
        $STATUSBAR update nightlight_icon=""
        pkill -SIGKILL wlsunset
    else
        $STATUSBAR update nightlight_icon=""
        wlsunset -t 4750 -T 5750 &
    end
end

function fix-xwayland-app-scaling
    systemctl --user start xsettingsd.service
    echo "Xft.dpi: 64" | xrdb -merge
    xprop -root -format _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 1
end


function update_vol
    set VOL (pamixer --get-volume)
    $STATUSBAR update vol="$VOL"
end


function get_vol_icon
    set MUTE (pamixer --get-mute)
    set VOL (pamixer --get-volume)

    if test "$MUTE" = true
        echo "󰝟"
        $STATUSBAR update $vol_icon="󰝟"
        return
    end

    if test $VOL -gt 66
        echo "󰕾"
        $STATUSBAR update $vol_icon="󰕾"
        return
    else if test $VOL -gt 33
        echo "󰖀"
        $STATUSBAR update $vol_icon="󰖀"
        return
    else
        echo "󰕿"
        $STATUSBAR update $vol_icon="󰕿"
        return
    end
end


function set_vol
    set percentage $argv[2]
    pamixer --set-volume $percentage
    volume
end

function toggle_mute
    pamixer --toggle-mute
    update_vol_icon
end

function increase_vol
    pamixer -i 5
    update_vol_icon
    update_vol
end

function decrease_vol
    pamixer -d 5
    update_vol_icon
    update_vol
end

function get_network_icon
    set TYPE (nmcli d | head -n 2 | tail -n 1 | awk '{print $2}')

    if test $TYPE = ethernet
        echo "󰈀 "
        return
    end

    if test $TYPE = wifi
        set SIGNAL_STRENGTH (string match -r "\d+" (cat /proc/net/wireless | tail -n 1 | awk '{print $3}'))
        set PERCENTAGE (math $SIGNAL_STRENGTH / 70)

        if test $PERCENTAGE -gt 0.75
            echo "󰤨 "
            return
        else if test $PERCENTAGE -gt 0.5
            echo "󰤥 "
            return
        else if test $PERCENTAGE -gt 0.25
            echo "󰤢 "
            return
        else if test $PERCENTAGE -gt 0
            echo "󰤟 "
            return
        else
            echo "󰤯 "
            return
        end
    end

    echo "󰲛"
end

function update_network_tooltip
    set TYPE (nmcli d | head -n 2 | tail -n 1 | awk '{print $2}')

    if test $TYPE = ethernet
        $STATUSBAR update network_tooltip="Ethernet"
        return
    end

    if test $TYPE = wifi
        set SSID (nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d: -f2)
        $STATUSBAR update network_tooltip="Wifi: $SSID"
        return
    end

    $STATUSBAR update network_tooltip="Disconnected"
end

switch $argv[1]
    case portal
        run-portal
    case import-gsettings
        import-gsettings
    case toggle-idle
        toggle-idle
    case toggle-nightlight
        toggle-nightlight
    case fix-xwayland-app-scaling
        fix-xwayland-app-scaling
    case volume
        get_vol_icon
        update_vol
    case network
        get_network_icon
        update_network_tooltip
    case volume_up
        increase_vol
    case volume_down
        decrease_vol
end
