#!/bin/fish

set CONFIG $HOME/.config/eww
set WIDGET eww --config $CONFIG

function spawn-bar
    killall -q jq
    killall -q eww
    eww daemon
    set pid (pgrep eww)
    if test -n "$pid"
        # GTK_DEBUG=interactive eww --config "$config" --debug open bar --screen 0
        eww --config "$CONFIG" --debug open bar --screen 0
    end
end

function toggle-bar
    set opened ($WIDGET windows | grep "*bar")

    if test -n "$opened"
        $WIDGET close bar
    else
        $WIDGET open bar
    end
end

switch $argv[1]
    case spawn-bar
        spawn-bar
    case toggle-bar
        toggle-bar
end
