#!/bin/bash

## See https://wiki.hyprland.org/Useful-Utilities/Status-Bars/#eww
function clamp {
	min=$1
	max=$2
	val=$3
	python -c "print(max($min, min($val, $max)))"
}

function change-active {
  direction=$1
  current=$2
  if test "$direction" = "down"
  then
	  target=$(clamp 1 6 $(($current+1)))
	  echo "jumping to $target"
    hyprctl dispatch workspace $target
  elif test "$direction" = "up"
  then
	  target=$(clamp 1 6 $(($current-1)))
	  echo "jumping to $target"
    hyprctl dispatch workspace $target
  fi
}

function get-active {
  hyprctl monitors -j | jq '.[] | select(.focused) | .activeWorkspace.id'
  socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - |
  stdbuf -o0 awk -F '>>|,' -e '/^workspace>>/ {print $2}' -e '/^focusedmon>>/ {print $3}'
}

function get {
  spaces (){
	  WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
	  seq 1 6 | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
  }

  spaces
  socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    spaces
  done
}

case $1 in
change-active)
  change-active
  ;;
get-active)
  get-active
  ;;
get)
  get
  ;;
esac
